# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: test
on: 
  pull_request:
    types: [opened]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Teams Notification
        uses: appleboy/teams-action@master
        with:
          url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "New Push Notification"
          summary: "A new pull request has been created in the repository by ${{ github.event.pull_request.user.login }}"
          text: "Title: ${{ github.event.pull_request.title }}\n\nDescription: ${{ github.event.pull_request.body }}"

